AWSTemplateFormatVersion: 2010-09-09
Parameters:
  OpenSearchDomainArn:
    Type: String
    Default: arn:aws:es:us-west-2:187751159313:domain/assurexemail
Resources:
  FirehoseBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: '7'
  SesStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: "ses-stream"
      DeliveryStreamType: "DirectPut"
      AmazonopensearchserviceDestinationConfiguration:
        DomainARN: !Ref OpenSearchDomainArn
        IndexName: "sesmessages"
        RoleARN: !GetAtt FirehoseRole.Arn
        S3BackupMode: "FailedDocumentsOnly"
        S3Configuration:
          BucketARN: !GetAtt FirehoseBucket.Arn
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: '50'
          RoleARN: !GetAtt DeliveryRole.Arn
    DependsOn:
      - FirehoseRole
      - FirehosePolicy
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
  FirehosePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: opensearch-delivery-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'es:*'
            Resource: 'arn:aws:es:us-west-2:187751159313:domain/assurexemail'
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !Sub "arn:aws:s3:::${FirehoseBucket}"
              - !Sub "arn:aws:s3:::${FirehoseBucket}*"
      Roles:
        - !Ref FirehoseRole
  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 'firehose'
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
          - Sid: 'ses'
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: 'sts:AssumeRole'
  DeliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose-delivery-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !Sub "arn:aws:s3:::${FirehoseBucket}"
              - !Sub "arn:aws:s3:::${FirehoseBucket}*"
          - Effect: Allow
            Action:
              - 'kinesis:GetShardIterator'
              - 'kinesis:GetRecords'
              - 'kinesis:DescribeStream'
              - 'kinesis:ListStreams'
            Resource: !GetAtt SesStream.Arn
          - Effect: Allow
            Action:
              - 'firehose:*'
            Resource: !GetAtt SesStream.Arn
      Roles:
        - !Ref DeliveryRole
  ConfigSet:
    Type: 'AWS::SES::ConfigurationSet'
    Properties:
      Name: 'TrackingSet'
  OpensearchEventDestination:
    Type: 'AWS::SES::ConfigurationSetEventDestination'
    Properties:
      ConfigurationSetName: !Ref ConfigSet
      EventDestination:
        Name: 'OpensearchTrackingDest'
        Enabled: true
        MatchingEventTypes:
          - send
          - reject
          - bounce
          - complaint
          - delivery
          - open
          - click
          - renderingFailure
        KinesisFirehoseDestination:
          DeliveryStreamARN: !GetAtt SesStream.Arn
          IAMRoleARN: !GetAtt DeliveryRole.Arn
    DependsOn:
      - SesStream
      - DeliveryPolicy
      - DeliveryRole
